spring:
  cloud:
    gateway:
      routes:
        - id: restaurant-route
          uri: ${RESTAURANT_ROUTE_URI:http://localhost:8081}
          predicates:
            - Path=/restaurant/**
          filters:
            - AddResponseHeader=X-Powered-By, Eric Gateway Service
        - id: user-route
          uri: ${USER_ROUTE_URI:http://localhost:8081}
          predicates:
            - Path=/user/**
          filters:
            - AddResponseHeader=X-Powered-By, Eric Gateway Service